In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df= pd.read_csv('train.txt', sep=';', header= None, names = ['text','emotion'])

In [13]:
df.head()

,text,emotion
0,i didnt feel humiliated,0
1,i can go from feeling so hopeless to so damned...,0
2,im grabbing a minute to post i feel greedy wrong,1
3,i am ever feeling nostalgic about the fireplac...,2
4,i am feeling grouchy,1


In [8]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [12]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]= i
    i +=1

df['emotion']= df['emotion'].map(emotion_numbers)

In [ ]:
df['text']= df['text'].apply(lambda x : x.lower()) # lowecasing

In [15]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [16]:
df['text'].apply(remove_punc)

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...                        
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: object

In [17]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [18]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)
     

In [19]:
import nltk

In [20]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [21]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jhaki\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jhaki\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [22]:
stop_words = set(stopwords.words('english'))

In [23]:
df.loc[1]['text']


'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [24]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [25]:

df['text'] = df['text'].apply(remove)
     

In [26]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [ ]:
# BAG OF WORDS using n grams
from sklearn.feature_extraction.text import CountVectorizer

documents= [
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizer = CountVectorizer(ngram_range=(1,2))

X= vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n", X.toarray())

Vocabulary: ['best' 'great' 'is' 'is great' 'is the' 'love' 'love pasta' 'love pizza'
 'pasta' 'pasta is' 'pizza' 'pizza is' 'the' 'the best']

BoW Matrix:
 [[0 0 0 0 0 1 0 1 0 0 1 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 1 1 0 0 0 0]]


In [30]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

documents= [
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizer = TfidfVectorizer()

X= vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n", X.toarray())

Vocabulary: ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

BoW Matrix:
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]
